[package]
name = "starnamics/rongo"
description = "MongoDB Atlas Data API wrapper for connecting Roblox to MongoDB"
version = "2.0.0"
license = "MIT"
realm = "server"
registry = "https://github.com/UpliftGames/wally-index"
exclude = [
  "LICENSE", "README.md"
]
